apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificateArn }}
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: {{ .Values.subnets }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.wafArn }}
    external-dns.alpha.kubernetes.io/hostname: "*.{{ .Values.baseDomain }}"
    kubernetes.io/ingress.class: alb
  name: alb-ingress-connect-nginx
  namespace: kube-system
spec:
  defaultBackend:
    service:
      name: ingress-nginx-controller
      port:
        name: https